src/p11_ec.c: check OPENSSL_NO_EC earlier
Function compute_key_fn uses types EC_POINT and EC_KEY which are defined
in ec.h. If OPENSSL_NO_EC is defined, no header file ec.h exists and
causes compile errors.

../../git/src/p11_ec.c:45:8: error: unknown type name 'EC_POINT'
  const EC_POINT *, const EC_KEY *,
        ^~~~~~~~
../../git/src/p11_ec.c:45:26: error: unknown type name 'EC_KEY'
  const EC_POINT *, const EC_KEY *,
                          ^~~~~~
So check OPENSSL_NO_EC earlier in src/p11_ec.c.

Signed-off-by: Kai Kang <kai.kang@windriver.com>